const T={"nl": {"name": "Naam", "age": "Leeftijd", "height": "Lengte (cm)", "weight": "Gewicht (kg)", "goal": "Doelgewicht (kg)", "prefs": "Niet lusten / voorkeuren", "allergies": "Allergieën / intoleranties", "start": "Start mijn plan", "healthTogether": "Samen gezonder", "weeks": "weken", "heroText": "Eten, bewegen en elkaar motiveren.", "goodDay": "Mooie dag!", "eatWell": "Lekker eten", "moveMore": "Meer bewegen", "together": "Samen volhouden", "sportOptions": "Sportmogelijkheden", "chooseActivities": "Wat heb jij ter beschikking?", "personal": "Persoonlijk", "equipmentNote": "Kies alles wat bij jou past. Je schema past zich automatisch aan.", "today": "Vandaag", "movement": "Beweging", "menu": "Menu", "community": "Community", "shareMoment": "Deel een moment", "addPhoto": "Foto toevoegen", "post": "Plaatsen", "liveNote": "Op dit moment blijven posts op je eigen toestel. Voor echte gedeelde foto's met vrienden koppelen we hierna de online database.", "weekMenu": "Weekmenu", "editMeals": "Pas gerechten aan", "reset": "Herstel", "progress": "Voortgang", "weightTitle": "Gewicht", "save": "Opslaan", "shopping": "Boodschappen", "list": "Lijst", "caption": "Wat wil je delen?", "good": "Goed bezig", "startpoint": "Startpunt", "foodPrefs": "Voorkeuren", "allergy": "Allergieën", "breakfast": "Ontbijt", "lunch": "Lunch", "snack": "Snack", "dinner": "Avond"}, "en": {"name": "Name", "age": "Age", "height": "Height (cm)", "weight": "Weight (kg)", "goal": "Goal weight (kg)", "prefs": "Food dislikes / preferences", "allergies": "Allergies / intolerances", "start": "Start my plan", "healthTogether": "Healthier together", "weeks": "weeks", "heroText": "Food, movement and motivating each other.", "goodDay": "Great day!", "eatWell": "Enjoy good food", "moveMore": "Move more", "together": "Keep going together", "sportOptions": "Activity options", "chooseActivities": "What do you have available?", "personal": "Personal", "equipmentNote": "Choose everything that suits you. Your plan adapts automatically.", "today": "Today", "movement": "Movement", "menu": "Menu", "community": "Community", "shareMoment": "Share a moment", "addPhoto": "Add photo", "post": "Post", "liveNote": "For now, posts stay on your own device. Next we can connect the online database for truly shared photos with friends.", "weekMenu": "Weekly menu", "editMeals": "Edit meals", "reset": "Reset", "progress": "Progress", "weightTitle": "Weight", "save": "Save", "shopping": "Shopping", "list": "List", "caption": "What would you like to share?", "good": "Great job", "startpoint": "Starting point", "foodPrefs": "Preferences", "allergy": "Allergies", "breakfast": "Breakfast", "lunch": "Lunch", "snack": "Snack", "dinner": "Dinner"}};
const PLANS={"nl": [["Volkoren brood + eieren + fruit", "Brood + kip/kaas + rauwkost", "Yoghurt + fruit", "Kip, aardappelen en groenten"], ["Yoghurt + banaan + bessen", "Wrap met kip en groenten", "Appel + noten", "Spaghetti bolognese met groenten"], ["Volkoren toast + roerei + fruit", "Soep + volkoren brood", "Yoghurt + fruit", "Kip of vis + puree + broccoli"], ["Kwark + fruit + granola", "Wrap met ei/kip + groenten", "Banaan + yoghurt", "Kip met rijst en wokgroenten"], ["Volkoren brood + kaas + fruit", "Brood + beleg + groenten", "Fruit + noten", "Pita kip + groenten + yoghurtsaus"], ["Broodjes + ei + fruit", "Soep + brood", "Yoghurt of fruit", "Hamburger + ovenaardappeltjes + salade"], ["Eieren + volkoren brood + fruit", "Restjes of broodmaaltijd", "Kleine traktatie of fruit", "Gehaktballetjes + aardappelen + groenten"]], "en": [["Wholegrain bread + eggs + fruit", "Bread + chicken/cheese + raw vegetables", "Yogurt + fruit", "Chicken, potatoes and vegetables"], ["Yogurt + banana + berries", "Chicken wrap + vegetables", "Apple + nuts", "Spaghetti bolognese with vegetables"], ["Wholegrain toast + scrambled eggs + fruit", "Soup + wholegrain bread", "Yogurt + fruit", "Chicken or fish + mash + broccoli"], ["Yogurt + fruit + granola", "Egg/chicken wrap + vegetables", "Banana + yogurt", "Chicken with rice and stir-fry vegetables"], ["Wholegrain bread + cheese + fruit", "Bread + toppings + vegetables", "Fruit + nuts", "Chicken pita + vegetables + yogurt sauce"], ["Bread rolls + egg + fruit", "Soup + bread", "Yogurt or fruit", "Burger + oven potatoes + salad"], ["Eggs + wholegrain bread + fruit", "Leftovers or bread lunch", "Small treat or fruit", "Meatballs + potatoes + vegetables"]]};
const E=[["walk","🚶","Wandelen","Walking"],["bike","🚲","Fietsen","Cycling"],["homebike","🚴","Hometrainer","Exercise bike"],["rower","🚣","Roeimachine","Rowing machine"],["gym","🏋️","Fitness","Gym"],["run","🏃","Lopen","Running"],["home","🏠","Thuis zonder materiaal","Home / no equipment"],["swim","🏊","Zwemmen","Swimming"]];
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
let lang=localStorage.getItem("gf_lang")||"nl",profiles=JSON.parse(localStorage.getItem("gf_profiles")||"[]"),activeId=localStorage.getItem("gf_active")||"",equipment=JSON.parse(localStorage.getItem("gf_equipment")||"{}"),tasks=JSON.parse(localStorage.getItem("gf_tasks")||"{}"),weights=JSON.parse(localStorage.getItem("gf_weights")||"{}"),overrides=JSON.parse(localStorage.getItem("gf_menu")||"{}"),posts=JSON.parse(localStorage.getItem("gf_posts")||"[]"),shopping=JSON.parse(localStorage.getItem("gf_shop")||"[]"),photo="";
const tr=k=>T[lang][k]||k,active=()=>profiles.find(p=>p.id===activeId)||profiles[0],uid=()=>Math.random().toString(36).slice(2,9);
function applyLang(){qsa("[data-t]").forEach(x=>x.textContent=tr(x.dataset.t));qsa("[data-ph]").forEach(x=>x.placeholder=tr(x.dataset.ph));qs("#langBtn").textContent=lang==="nl"?"EN":"NL";}
function openOnboard(){qs("#onboarding").classList.remove("hidden")}function closeOnboard(){qs("#onboarding").classList.add("hidden")}
qs("#createProfile").onclick=()=>{let p={id:uid(),name:qs("#name").value.trim(),age:+qs("#age").value,height:+qs("#height").value,weight:+qs("#weight").value,goal:+qs("#goal").value,prefs:qs("#prefs").value.trim(),allergies:qs("#allergies").value.trim()};if(!p.name||!p.age||!p.height||!p.weight||!p.goal)return alert(lang==="nl"?"Vul alle basisgegevens in.":"Fill in all basic details.");profiles.push(p);activeId=p.id;equipment[p.id]=["walk","home"];weights[p.id]=[p.weight];saveCore();closeOnboard();render();}
function saveCore(){localStorage.setItem("gf_profiles",JSON.stringify(profiles));localStorage.setItem("gf_active",activeId);localStorage.setItem("gf_equipment",JSON.stringify(equipment));localStorage.setItem("gf_weights",JSON.stringify(weights));}
function renderProfiles(){qs("#profiles").innerHTML=profiles.map(p=>`<button class="profile ${p.id===activeId?"active":""}" data-p="${p.id}"><div class="avatar">${p.name[0].toUpperCase()}</div><div><b>${p.name}</b><small>${p.weight} kg · ${p.age}</small></div></button>`).join("");qsa("[data-p]").forEach(b=>b.onclick=()=>{activeId=b.dataset.p;saveCore();render();})}
function renderEquipment(){let p=active(),sel=equipment[p.id]||[];qs("#equipmentGrid").innerHTML=E.map(e=>`<button class="equip ${sel.includes(e[0])?"selected":""}" data-e="${e[0]}"><span class="emoji">${e[1]}</span><b>${lang==="nl"?e[2]:e[3]}</b></button>`).join("");qsa("[data-e]").forEach(b=>b.onclick=()=>{let a=equipment[p.id]||[],i=a.indexOf(b.dataset.e);i>=0?a.splice(i,1):a.push(b.dataset.e);equipment[p.id]=a;saveCore();renderEquipment();renderMovement();})}
function movementOptions(){let sel=equipment[active().id]||[],o=[];if(sel.includes("walk"))o.push(["🚶",lang==="nl"?"Wandelen":"Walking","15–20 min"]);if(sel.includes("bike"))o.push(["🚲",lang==="nl"?"Fietsen":"Cycling","15–25 min"]);if(sel.includes("homebike"))o.push(["🚴",lang==="nl"?"Hometrainer":"Exercise bike","10–20 min"]);if(sel.includes("rower"))o.push(["🚣",lang==="nl"?"Roeimachine":"Rowing machine","5–15 min"]);if(sel.includes("gym"))o.push(["🏋️",lang==="nl"?"Fitness":"Gym","20 min"]);if(sel.includes("run"))o.push(["🏃",lang==="nl"?"Wandelen + korte jog":"Walk + short jogs","10–15 min"]);if(sel.includes("home"))o.push(["🏠",lang==="nl"?"Thuis bewegen":"Home movement","10–15 min"]);if(sel.includes("swim"))o.push(["🏊",lang==="nl"?"Zwemmen":"Swimming","15–25 min"]);return o.length?o.slice(0,3):[["🌿",tr("movement"),"10 min"]];}
function renderMovement(){let o=movementOptions(),p=active();qs("#movementTasks").innerHTML=o.map((x,i)=>{let k=p.id+"_"+i;return `<label class="task"><input type="checkbox" data-task="${k}" ${tasks[k]?"checked":""}><div class="icon">${x[0]}</div><div class="meta"><strong>${x[1]}</strong><small>${x[2]}</small></div></label>`}).join("");qsa("[data-task]").forEach(c=>c.onchange=e=>{tasks[e.target.dataset.task]=e.target.checked;localStorage.setItem("gf_tasks",JSON.stringify(tasks));})}
function planKey(){return active().id+"_"+lang}function currentPlan(){return overrides[planKey()]||PLANS[lang].map(x=>[...x])}
function renderMeals(){let p=active(),plan=currentPlan(),d=(new Date().getDay()+6)%7,n=[tr("breakfast"),tr("lunch"),tr("snack"),tr("dinner")],ic=["🍳","🥪","🍎","🍽️"];qs("#mealList").innerHTML=plan[d].map((m,i)=>`<div class="meal"><div class="icon">${ic[i]}</div><div class="meta"><strong>${n[i]}</strong><small>${m}</small></div></div>`).join("");qs("#foodNote").textContent=[p.prefs?tr("foodPrefs")+": "+p.prefs:"",p.allergies?tr("allergy")+": "+p.allergies:""].filter(Boolean).join(" • ");qs("#kcalBadge").textContent=tr("startpoint")+" ± "+Math.round((10*p.weight+6.25*p.height-5*p.age-100)*1.2-300)+" kcal";renderEditor();}
function renderEditor(){let plan=currentPlan(),days=lang==="nl"?["Ma","Di","Wo","Do","Vr","Za","Zo"]:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],names=[tr("breakfast"),tr("lunch"),tr("snack"),tr("dinner")];qs("#menuEditor").innerHTML=plan.map((d,di)=>`<div class="editor-day"><h4>${days[di]}</h4><div class="editor-grid">${d.map((m,mi)=>`<label><small>${names[mi]}</small><textarea data-di="${di}" data-mi="${mi}">${m}</textarea></label>`).join("")}</div></div>`).join("");qsa("#menuEditor textarea").forEach(t=>t.onchange=e=>{let p=currentPlan().map(d=>[...d]);p[+e.target.dataset.di][+e.target.dataset.mi]=e.target.value;overrides[planKey()]=p;localStorage.setItem("gf_menu",JSON.stringify(overrides));renderMeals();})}
function renderWeight(){let p=active(),arr=weights[p.id]||[p.weight],cur=arr[arr.length-1],pct=Math.max(0,Math.min(100,((p.weight-cur)/(p.weight-p.goal))*100));qs("#currentWeight").textContent=cur.toFixed(1)+" kg";qs("#weightGoal").textContent=tr("goal")+": "+p.goal+" kg";qs("#weightBar").style.width=pct+"%";}
function defaultShop(){return (lang==="nl"?["Volkoren brood","Eieren","Kip","Yoghurt","Fruit","Groenten","Aardappelen","Rijst"]:["Wholegrain bread","Eggs","Chicken","Yogurt","Fruit","Vegetables","Potatoes","Rice"]).map(x=>({n:x,d:false}))}
function renderShop(){if(!shopping.length)shopping=defaultShop();qs("#shopping").innerHTML=shopping.map((x,i)=>`<label class="shop ${x.d?"done":""}"><input type="checkbox" data-s="${i}" ${x.d?"checked":""}><label>${x.n}</label></label>`).join("");qsa("[data-s]").forEach(c=>c.onchange=e=>{shopping[+e.target.dataset.s].d=e.target.checked;localStorage.setItem("gf_shop",JSON.stringify(shopping));renderShop();})}
function renderFeed(){let em=["❤️","🔥","💪","😋","👏","😂"];qs("#feed").innerHTML=[...posts].reverse().map(p=>`<div class="post-card"><div class="post-top"><div class="avatar">${p.name[0]}</div><div><b>${p.name}</b><small>${new Date(p.date).toLocaleString()}</small></div></div>${p.photo?`<img src="${p.photo}">`:""}<div class="post-body"><p>${p.caption||""}</p><div class="reactions">${em.map(e=>`<button class="reaction" data-r="${p.id}" data-em="${e}">${e} ${(p.reactions&&p.reactions[e])||0}</button>`).join("")}</div></div></div>`).join("");qsa("[data-r]").forEach(b=>b.onclick=()=>{let p=posts.find(x=>x.id===b.dataset.r);p.reactions=p.reactions||{};p.reactions[b.dataset.em]=(p.reactions[b.dataset.em]||0)+1;localStorage.setItem("gf_posts",JSON.stringify(posts));renderFeed();})}
function render(){applyLang();if(!profiles.length)return openOnboard();if(!activeId)activeId=profiles[0].id;let p=active();qs("#heroTitle").textContent=tr("good")+", "+p.name+"! 🌟";renderProfiles();renderEquipment();renderMovement();renderMeals();renderWeight();renderShop();renderFeed();}
qs("#addProfile").onclick=openOnboard;qs("#langBtn").onclick=()=>{lang=lang==="nl"?"en":"nl";localStorage.setItem("gf_lang",lang);shopping=[];render();};qs("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");qs("#themeBtn").textContent=document.body.classList.contains("dark")?"🌙":"☀️";};
qs("#saveWeight").onclick=()=>{let v=parseFloat(qs("#weightInput").value),p=active();if(!v)return;weights[p.id]=weights[p.id]||[];weights[p.id].push(v);saveCore();qs("#weightInput").value="";renderWeight();}
qs("#addShop").onclick=()=>{let v=qs("#shopInput").value.trim();if(!v)return;shopping.push({n:v,d:false});localStorage.setItem("gf_shop",JSON.stringify(shopping));qs("#shopInput").value="";renderShop();}
qs("#resetMenu").onclick=()=>{delete overrides[planKey()];localStorage.setItem("gf_menu",JSON.stringify(overrides));renderMeals();}
let emojis=["❤️","🔥","💪","😋","👏","😂","🥗","🚴","🚣"];qs("#composerEmojis").innerHTML=emojis.map(e=>`<button>${e}</button>`).join("");qsa("#composerEmojis button").forEach(b=>b.onclick=()=>qs("#caption").value+=(qs("#caption").value?" ":"")+b.textContent);
qs("#photoInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=x=>{photo=x.target.result;qs("#photoPreview").src=photo;qs("#photoPreview").classList.remove("hidden")};r.readAsDataURL(f);}
qs("#postBtn").onclick=()=>{let c=qs("#caption").value.trim();if(!c&&!photo)return;let p=active();posts.push({id:uid(),name:p.name,date:new Date().toISOString(),caption:c,photo,reactions:{}});try{localStorage.setItem("gf_posts",JSON.stringify(posts))}catch(e){alert(lang==="nl"?"Foto te groot om lokaal op te slaan.":"Photo is too large to save locally.");posts.pop();return}qs("#caption").value="";photo="";qs("#photoPreview").classList.add("hidden");renderFeed();}
render();
w
